### ISSUE TITLE
Paper #O: "Is Neuron Coverage a Meaningful Measure for Testing Deep Neural Networks?"

### ISSUE THREAD

**Issue by kstolee** [researchart/fse20#105]
This issue is for discussion related to PR #23 

Author contact: @fabrieceyhc

**Comment by kstolee** [comment]
# Authors

| Author               | Email                 | GitHub Usename | GitHubID | Corresponding Author |
| -------------------- | --------------------- | -------------- | -------- | -------------------- |
| Fabrice Harel-Canada | fabricehc@cs.ucla.edu | fabriceyhc     | 4616809  | Yes                  |
| Lingxiao Wang        | lingxw@cs.ucla.edu    | leowang7267    | 24538462 |                      |
| Muhammad Ali Gulzar  | gulzar@cs.ucla.edu    | maligulzar     | 4046641  |                      |
| Quanquan Gu          | qgu@cs.ucla.edu       | uclaml         | 22385378 |                      |
| Miryung Kim          | miryung@cs.ucla.edu   | miryung        | 9385024  |                      |

**Comment by art-reviewer** [comment]
[Paper](https://github.com/fabriceyhc/fse20/blob/8711e2fec7852ee9e500ac90e3220268a1d8360e/submissions/reusable/nc_diversity_attacks/Is%20Neuron%20Coverage%20a%20Meaningful%20Measure%20for%20Testing%20Deep%20Neural%20Networks.pdf)

**Comment by letmecheckthat** [comment]
Thank you for sharing your code. I have inspected the code and run the notebook to reproduce the reported results from the shared data file; everything checks out.

Note that I have not (yet) tried the VM-based setup. The Self-setup completing successfully ticks the 'functional' box, in my opinion. One note about that VM setup, though, is that the image appears to be uploaded on Google Drive, which is not an archival repository. It would help the "Availability" of this artifact to archive it as well.

The main issue I ran into while setting this up was the versioning of dependencies: several of the specified packages are not compatible with Python 3.8, including `pandas`, `matplotlib`, and `scipy` (at least, on Windows). I ran the notebook with the latest version of these packages instead and that worked just fine. Please either update the documentation to specify this limitation (right now it states "Python 3.7.3+"), or update the stated dependency versions to more recent versions. I also missed one package, called `seaborn`, that is not listed in the requirements; please update.

**Comment by fabriceyhc** [comment]
I think I may have misunderstood something about the evaluation process. I intended the VM option only for the FSE review team - just to make it easier for you - and don't plan on making it available in the GitHub long-term. Would it be acceptable to remove that option and just consider the self-setup? I will take care of the versioning issue and add seaborn as well.

**Comment by letmecheckthat** [comment]
That definitely makes sense, thanks for adding that for us. I personally think it's quite fine to leave the VM option in there as it might be more convenient for others (incl. non-reviewers down the line), but it certainly isn't necessary. If the concern is badges, its presence doesn't affect that imo; I think they are all appropriate for just the Self-setup option (incl. Available). Your call.

**Comment by fabriceyhc** [comment]
Thanks for understanding. If the VM was more powerful / had GPU computation then it would be more of a useful resource, but I don't think people will get much out of it. It was just intended to show that the scripts do indeed work. I'll take care of all the revisions today.

**Comment by fabriceyhc** [comment]
Hi there, I made the edits and created another pull request for you. My apologies if that wasn't the correct process - just let me know I'll revise. 

https://github.com/researchart/fse20/pull/129

Basically, I just went through and updated the requirements.txt file using the `~=` operator, which pulls the most compatible version of the package given your version of python ([link](https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format)). Hopefully this resolves both situations where the Python version is either higher or lower than the one I used.

**Comment by FSEArtifactReviewer835** [comment]
Requested Badge: Reusable

Summary/Overview:
The artifact contains evaluations used in the paper to investigate the relationship of neural coverage with defect detection, naturalness, and output impartiality.  As the work is evaluating deep neural network measures (which can take a long time to train), the authors have included results and pre-trained models in the package, along with the three datasets mentioned in the paper (MINST, CIFAR10, and the self-driving images).

I was able to do the manual set up and run your Python notebook (using the self-set up) and reconstruct most of the results from the paper, though the file raised a few warnings.  I have tried running the python scripts as well, though I haven't been able to get GPU enabled PyTorch working properly on the machine I'm testing them on. Therefore, I haven't been able to validate results from these scripts (other than whether they run or crash) as they are taking a very long time to run.  The scripts for the CIFAR and MNIST data seem to be running fine, but for the self-driving data, there is a 'data/udacity_self_driving_car/targets.csv' file that seems to be missing from the data that causes them to crash.  Also, make sure the 'logs' directory is created beforehand.  I had to do that to get the scripts to run.

I think this artifact could qualify for Reusable if this missing data is addressed.  Validating long-running scripts is a challenge, so I  appreciate that the prior results were saved and that the results from the paper could be reconstructed.

Basic Requirements:
CONTACT.md - Present, author contact information is listed.
README.md - Present
INSTALL.md - Present, Lists required packages and versions needed.
STATUS.md - Present, requested badges and reasons listed are present)
LICENSE.md - Present, MIT License
Accepted Paper - Present


Details:
pearson_vs_spearman_correlations.pdf - Table 4 matches first block (Looks like they reported Pearson correlations)

Table 5 looks like it matches the two middle (bottom halves) in the pdf.

Table 6 matches the 4th set.

I'm not sure how to reconstruct the data for Table 7?

Directory ‘imgs’ contains the figure results in the paper.  They appear to line up.

Jupyter notebook reproduces the results from the paper.
Jupyter notebook loads with results.  When running, I’ve gotten up to 21 without
warnings (but I see warnings “/home/ccasal/anaconda3/lib/python3.7/site-packages/matplotlib/tight_layout.py:199: UserWarning: Tight layout not applied. tight_layout cannot make axes width small enough to accommodate all axes decorations
  warnings.warn('Tight layout not applied. '
/home/ccasal/anaconda3/lib/python3.7/site-packages/seaborn/axisgrid.py:1847: UserWarning: JointGrid annotation is deprecated and will be removed in a future release.
  warnings.warn(UserWarning(msg))
“)  
    - I think this might because I’m using 3.7.7 instead of 3.7.3, but the plots seem to be generating anyways.
However, the rest of the file can finish running even with the warnings.

python _PGD_div_mnist.py
- Fails with   File "_PGD_div_mnist.py", line 111, in main
    with open('logs/pgd_mnist_error_log_' + str(date) + '.txt', 'w') as error_log:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/pgd_mnist_error_log_2020-06-13.txt'

Fix - mkdir logs (Seems to fix the issue - recommend that authors fix this)
However, this script does seem to take some time to complete (I'm stuck with a CPU only version at the moment.)


python _PGD_div_driving.py and _CW_div_driving.py fail with FileNotFoundError: [Errno 2] File b'data\\udacity_self_driving_car/targets.csv
- Did you forget to add the targets.csv file?

The other 4 python scripts have been running successfully for me, but as PyTorch doesn't seem to recognize the installation of CUDA I'm using properly, the CPU bound versions are taking a very long time to complete.

**Comment by fabriceyhc** [comment]
- I'm not sure how to reconstruct the data for Table 7?

The code submitted was used for the primary correlation evaluation and I did not include the jupyter notebooks used to generate Table 7 or Figures 2, 3, 6. Would you like me to create another pull request for those items? 

- `python _PGD_div_mnist.py` issues

I will go back and add an empty logs folder to the repo so that the path resolves correctly. 

- `python _PGD_div_driving.py` & `python _CW_div_driving.py` issues

I accidentally renamed the file `final_example.csv` in the pull request. The `targets_file` for the `car_loader` can be changed from it's default but I'll rename the file so that it matches with the default in the script. 

And lastly, yeah, the scripts will take a long time. I ran them concurrently via Google Cloud with GPUs on Google Cloud (NVIDIA V100) and on my laptop (GeForce RTX 2060) and it still took many, many hours.

**Comment by FSEArtifactReviewer835** [comment]
Okay, on running it with the updates I see 2 issues.

1) The data path is hardcoded to a windows style format for _PGD_div_driving.py and _CW_div_driving.py  (see data_dir = r'data\udacity_self_driving_car').  It should be able to run on other systems (I'm using Linux and was able to quick fix this with data_dir = r'data/udacity_self_driving_car', but this should be more robust).
2) Even after fixing this, I get another error:
Traceback (most recent call last):
  File "_PGD_div_driving.py", line 66, in <module>
    inputs, targets, classes = generate_batch_reg(dataset, class_distribution, device)
  File "/FSEArtifacts/fse20/submissions/reusable/nc_diversity_attacks/utils.py", line 358, in generate_batch_reg
    inputs, targets, classes = next(iter(data_loader))
  File "/anaconda3/envs/FSEReviews/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/anaconda3/envs/FSEReviews/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/anaconda3/envs/FSEReviews/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/anaconda3/envs/FSEReviews/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/FSEArtifacts/fse20/submissions/reusable/nc_diversity_attacks/utils.py", line 464, in __getitem__
    paths = self.img_paths[idx]
IndexError: list index out of range

**Comment by fabriceyhc** [comment]
I appreciate the concern for code being OS-agnostic so I've corrected the path formatting accordingly.

Evidence of correctness in Linux:

![image](https://user-images.githubusercontent.com/4616809/85207740-ca515380-b2df-11ea-817d-d87d1bb0ee8f.png)

Preserved functionality on Windows:

![image](https://user-images.githubusercontent.com/4616809/85207767-0389c380-b2e0-11ea-9915-1268ea4e3648.png)

New PR: https://github.com/researchart/fse20/pull/137

**Comment by letmecheckthat** [comment]
Thanks for the updates. Can confirm the above functionality (`_CW_div_driving`) works on Windows from a fresh setup. I'm good for Reusable + Available (and Functional, naturally).

Please note one minor issue: I had to use the following command (from PyTorch's website) on Windows to install PyTorch & TorchVision:
```pip install torch==1.5.0+cu101 torchvision==0.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html```
This is a known issue on Windows; the rest of the `requirements.txt` file worked fine in a clean (conda) env after removing those two packages. Might be worth mentioning in the install guide.

**Comment by FSEArtifactReviewer835** [comment]
Okay, I pulled the newest update and the scripts that were breaking now work for me.  

"The code submitted was used for the primary correlation evaluation and I did not include the jupyter notebooks used to generate Table 7 or Figures 2, 5, and 6 or the DeepXplore comparison. Would you like me to create another pull request for those items?"

I think it would be nice to include these notebooks if you have them.

**Comment by fabriceyhc** [comment]
> Okay, I pulled the newest update and the scripts that were breaking now work for me.
> 
> "The code submitted was used for the primary correlation evaluation and I did not include the jupyter notebooks used to generate Table 7 or Figures 2, 5, and 6 or the DeepXplore comparison. Would you like me to create another pull request for those items?"
> 
> I think it would be nice to include these notebooks if you have them.

I've created PR #140 for this and wanted to highlight the check-in description for it:

> My apologies for these notebooks / .py files being rather chaotic. They served as a scratch pad for many of the side investigations that I worked on over the course of the main correlation evaluation. Unfortunately, most of the code is no longer runnable due to code drift, no longer having the pickle files I loaded up back then, etc. The main value I can see in them is that they still have most of the results I used for the paper in the output cells so that you can have some confidence that they're legit. 
> 
> Ultimately, I wouldn't merge these changes into the final repo because they're not really presentation worthy - I merely offer them up per your request.

**Comment by fabriceyhc** [comment]
> Thanks for the updates. Can confirm the above functionality (`_CW_div_driving`) works on Windows from a fresh setup. I'm good for Reusable + Available (and Functional, naturally).
> 
> Please note one minor issue: I had to use the following command (from PyTorch's website) on Windows to install PyTorch & TorchVision:
> `pip install torch==1.5.0+cu101 torchvision==0.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`
> This is a known issue on Windows; the rest of the `requirements.txt` file worked fine in a clean (conda) env after removing those two packages. Might be worth mentioning in the install guide.

Great, I'm glad to hear it's working now :) 

Regarding PyTorch, it looks like you have access to a GPU to run the cuda-enabled version. I mention in the install.md file: 
> If you have access to GPUs, [download](https://pytorch.org/get-started/locally/) the appropriate version of PyTorch for your system instead of using the default above. 

Is this an acceptable handling for your situation? Perhaps it may be better to leave PyTorch / TorchVision out of the `requirements.txt` altogether and just reference the download link since the command changes pretty regularly and they differ based on the OS?

**Comment by letmecheckthat** [comment]
Good point about the GPU-specific versions; I think there's a tangled issue of Windows and/or CUDA here, where the issue would exist even without a GPU (there is a `cpuonly` link on PyTorch's website as well), but that's hard to test. Maybe it's easiest to just make this a separate item. Anyways, this is an incredibly minor issue, so whatever you decide should be fine :)

**Comment by fabriceyhc** [comment]
> Good point about the GPU-specific versions; I think there's a tangled issue of Windows and/or CUDA here, where the issue would exist even without a GPU (there is a `cpuonly` link on PyTorch's website as well), but that's hard to test. Maybe it's easiest to just make this a separate item. Anyways, this is an incredibly minor issue, so whatever you decide should be fine :)

I agree that it's minor, but it's also an easy thing to accommodate and potentially helpful for others down the line. Here's a new PR for it: #147 

Thanks for the feedback :)

**Comment by FSEArtifactReviewer835** [comment]
> > Okay, I pulled the newest update and the scripts that were breaking now work for me.
> > "The code submitted was used for the primary correlation evaluation and I did not include the jupyter notebooks used to generate Table 7 or Figures 2, 5, and 6 or the DeepXplore comparison. Would you like me to create another pull request for those items?"
> > I think it would be nice to include these notebooks if you have them.
> 
> I've created PR #140 for this and wanted to highlight the check-in description for it:
> 
> > My apologies for these notebooks / .py files being rather chaotic. They served as a scratch pad for many of the side investigations that I worked on over the course of the main correlation evaluation. Unfortunately, most of the code is no longer runnable due to code drift, no longer having the pickle files I loaded up back then, etc. The main value I can see in them is that they still have most of the results I used for the paper in the output cells so that you can have some confidence that they're legit.
> > Ultimately, I wouldn't merge these changes into the final repo because they're not really presentation worthy - I merely offer them up per your request.

Okay, I took a look through the files and I see what you mean about them not being the easiest to follow.  I would be all right awarding the Available, Functional, Reusable badges with the following change:  In the main README.md file, include a section describing which Tables/Figures can be reconstructed from your main Jupyter notebook and which can't.  Essentially, a section similar to what you've told me here.

I'll leave it up to the authors if they want to keep the other notebooks in the artifact (or if the other reviewer feels they should be included).  If you do, perhaps you could put them in extra folder with a README.md explaining what you said in #140 and an overview of the notebooks for people interested in viewing the code and the saved results.

**Comment by fabriceyhc** [comment]
> Okay, I took a look through the files and I see what you mean about them not being the easiest to follow. I would be all right awarding the Available, Functional, Reusable badges with the following change: In the main README.md file, include a section describing which Tables/Figures can be reconstructed from your main Jupyter notebook and which can't. Essentially, a section similar to what you've told me here.

I've added another check-in to PR #147 to clarify in the README that certain figures / tables cannot be created from this repository with the understanding that they are ancillary to the primary correlation effort. 

If this is acceptable for everyone, I'll add one more PR to revert #140 and we should have a clean repo ready to go :)

**Comment by gousiosg** [comment]
It looks like there is agreement in providing all badges. @letmecheckthat and @FSEArtifactReviewer835 thanks for guiding @fabriceyhc to update his artifact; @fabriceyhc well done!

**Comment by fabriceyhc** [comment]
Thank you everyone!
