### ISSUE TITLE
Paper #M: Detecting Optimization Bugs in Database Engines via Non-Optimizing Reference Engine Construction

### ISSUE THREAD

**Issue by kstolee** [researchart/fse20#93]
This issue is for discussion related to PR #33 

Author contact: @mrigger

**Comment by kstolee** [comment]
# Authors

## Manuel Rigger

* Email: manuel.rigger@inf.ethz.ch
* GitHub ID: mrigger

## Zhendong Su

* Email: zhendong.su@inf.ethz.ch
* GitHub ID: zhendongsu

**Comment by art-reviewer** [comment]
[Paper](https://github.com/mrigger/fse20/blob/92d1d63939fe9a05082af36f19066bf6416e710d/submissions/reusable/315-NoREC-Rigger/NoREC.pdf)

**Comment by a-nice-reviewer** [comment]
### Video with instructions

- nice job, very comprehensive
- It would be nice if mentions to `video.mp4` had a hyperlink to the respective file.

### Tool

I was able to run the tool successfully and to query the results database.
I have got something like the following:

```
java -jar SQLancer-0.0.1-SNAPSHOT.jar sqlite3 --oracle NoREC
[2020/06/17 16:50:46] Executed 96533 queries (19283 queries/s; 3,20/s dbs, successful statements: 92%). Threads shut down: 0.
[2020/06/17 16:50:51] Executed 206488 queries (21999 queries/s; 0,00/s dbs, successful statements: 92%). Threads shut down: 0.
[2020/06/17 16:50:56] Executed 343509 queries (27431 queries/s; 0,00/s dbs, successful statements: 92%). Threads shut down: 0.
[2020/06/17 16:51:01] Executed 476356 queries (26569 queries/s; 0,00/s dbs, successful statements: 92%). Threads shut down: 0.
[2020/06/17 16:51:06] Executed 618386 queries (28417 queries/s; 0,00/s dbs, successful statements: 92%). Threads shut down: 0.
[2020/06/17 16:51:11] Executed 754806 queries (27316 queries/s; 0,00/s dbs, successful statements: 92%). Threads shut down: 0.
```

In the instructions it was not clear to me how I can get the results from running the tool:

- Can I stop it at any time?
  - EDIT: I understood by watching the video that the tool will stop when a bug is successfully detected.
- What does it mean having 92% successful statements?

Finally, the tool is publicly available with an open-source license (MIT).

### Results db

Finally, I used sqlite3 to query the results database `bugs.db`. I did not look for inconsistencies between my output and the data presented in the paper, but overall they seemed alright.

### Final remarks

I am in favor of giving this work the Reusable badge.

**Comment by mrigger** [comment]
Thank you very much for the useful feedback, @a-nice-reviewer! We have incorporated your comments to create an improved version of the artifact.

> * It would be nice if mentions to `video.mp4` had a hyperlink to the respective file.

We have added links to the video (see https://github.com/mrigger/fse20/commit/059d692784295f9d862c21799a52963942bbc3be).

> In the instructions it was not clear to me how I can get the results from running the tool:
> 
> * Can I stop it at any time?
>   
>   * EDIT: I understood by watching the video that the tool will stop when a bug is successfully detected.

The shortcut CTRL+C can be used to terminate SQLancer manually. If SQLancer does not find any bugs, it executes infinitely. The option `--num-tries` controls after how many bugs SQLancer terminates. Alternatively, the option `--timeout-seconds` can be used to specify the maximum duration that SQLancer is allowed to run. We have added this paragraph to the `INSTALL.md` document (see https://github.com/mrigger/fse20/commit/cbeb56a8a817fafb3e9161aac30435908bdd9dac).

> * What does it mean having 92% successful statements?

While SQLancer generates syntactically correct statements and queries, not all of them can be successfully executed by the DBMS. For example, an `INSERT` statement can fail when a constraint on a table or column is violated. As another example, a query can fail when division-by-zero error occurs. The successful statements metric specifies the percentage of statements that are executed without an error by the DBMS. We have added a description of this to the `INSTALL.md` document (see https://github.com/mrigger/fse20/commit/1bf518a3ed60b61e4325247076ea1655200ba686).

**Comment by a-nice-reviewer** [comment]
Thank you @mrigger for the clarification and for improving the instructions based on my comments. How can I see those changes—are they in the PR?

**Comment by mrigger** [comment]
I have integrated the changes into my personal repository at https://github.com/mrigger/fse20/. You can view the changes there, or by clicking on the above links to see how we addressed each concern individually. As another option, I have now also created a PR to integrate the changes into this repository (see #134).

**Comment by AnonReviewer626** [comment]
I congratulate the authors on this ingenious project.

## Available

The DOI works, so we can award this badge.

## Functional

I am willing to award this badge but would like to see some nits addressed.

- Documentation -- good.
- Consistent -- yes
- Complete -- yes
- Exercisable -- Mostly

re: Exercisable...

1. I have trouble matching the paragraph "Bugs found only by PQS" to the output of the associated query:

```
sqlite> SELECT COUNT(*) as count, reason FROM PQS_BUGS WHERE NOT reproducible_with_norec GROUP BY reason;
3|aggregate
3|distinct
1|intersect
1|leftjoin
18|unknown
```

You say "unknown" here, but the corresponding paragraph in the paper gives a range of reasons. Are they unknown or not?
 
(Related writing suggestion -- can you state the total number of bugs at the beginning of the paragraph in the manuscript? When I read it the first two times, I thought you were saying there were 18 total bugs, broken down by 3-3-1-1 (and a bunch of unknowns).

2. It is a bit odd that the database columns don't quite match the table columns for Tables 2 and 3. Consider tweaking the schema, munging the query so that the columns match, or giving the mapping in the README.

## Reusable

The documentation and structuring of this artifact is exemplary. However, I have some concerns "re-using it" and am not willing to grant the badge at the moment. Here are my issues:

1. The documentation should indicate how long sqlancer will run if invoked without num-tries or timeout-seconds, and give your machine specs (or state that this information can be found in the paper).

2. The artifact suggests `--num-tries` or `--timeout-seconds` to control how long the program runs for. These do not work as of commit 41986ce4302b0 on the sqlancer project. 

I also could not get `--num-threads` to work, so I begin to suspect my Docker image, which is:

 `openjdk                                               
 11-jre-slim                                  030d68516e3a`.

Here is the error output:

```
root@6cd7c05d5a6a:/sqlancer/target# java -jar SQLancer-0.0.1-SNAPSHOT.jar sqlite3 --oracle NoREC --num-tries 5
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter '--num-tries' but no main parameter was defined in your arg class
	at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:954)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:755)
	at com.beust.jcommander.JCommander.parse(JCommander.java:356)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:796)
	at com.beust.jcommander.JCommander.parse(JCommander.java:356)
	at com.beust.jcommander.JCommander.parse(JCommander.java:335)
	at sqlancer.Main.executeMain(Main.java:296)
	at sqlancer.Main.main(Main.java:273)
root@6cd7c05d5a6a:/sqlancer/target# java -jar SQLancer-0.0.1-SNAPSHOT.jar sqlite3 --oracle NoREC --timeout-seconds 60
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter '--timeout-seconds' but no main parameter was defined in your arg class
	at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:954)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:755)
	at com.beust.jcommander.JCommander.parse(JCommander.java:356)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:796)
	at com.beust.jcommander.JCommander.parse(JCommander.java:356)
	at com.beust.jcommander.JCommander.parse(JCommander.java:335)
	at sqlancer.Main.executeMain(Main.java:296)
	at sqlancer.Main.main(Main.java:273)
```

Please advise, or remove this paragraph from the docs.

**Comment by mrigger** [comment]
Thank you very much for the useful feedback, @AnonReviewer626! We have incorporated your comments to create an improved version of the artifact (see https://github.com/researchart/fse20/pull/143). Please find our response inline.

> re: Exercisable...
> 
> 1. I have trouble matching the paragraph "Bugs found only by PQS" to the output of the associated query:
> 
> ```
> sqlite> SELECT COUNT(*) as count, reason FROM PQS_BUGS WHERE NOT reproducible_with_norec GROUP BY reason;
> 3|aggregate
> 3|distinct
> 1|intersect
> 1|leftjoin
> 18|unknown
> ```
> 
> You say "unknown" here, but the corresponding paragraph in the paper gives a range of reasons. Are they unknown or not?

We carefully studied the test cases, and analyzed the reasons for the PQS bugs that could not be reproduced by NoREC. Since `unknown` is clearly misleading, we have renamed it to `nooptimization` (see https://github.com/mrigger/fse20/commit/7d20374de81f1d25c5d8db28737d694ef64abc9a). This category is rather broad, and, as stated in the paper, encompasses bugs that consistently compute an incorrect result, both in the unoptimized and optimized case:
> By far the most common kind of bugs that were detected by PQS, but not by NoREC, stem from the incorrect implementation of operators, functions, and other features (especially affinity conversions in SQLite), both in the optimized and unoptimized case.

For example, consider the following first test case from `PQS_BUGS` (see https://www.sqlite.org/src/tktview/3182d3879020ef3b2e6db56be2470a0266d3c773):

```sql
CREATE TABLE test (c1 TEXT PRIMARY KEY) WITHOUT ROWID;
CREATE INDEX index_0 ON test(c1 COLLATE NOCASE);
INSERT INTO test(c1) VALUES ('A');
INSERT INTO test(c1) VALUES ('a');
SELECT * FROM test; -- only one row is fetched
```
Due to a bug in the implementation of `WITHOUT ROWID` tables, the `COLLATE NOCASE` yielded an incorrect result, both in the optimized and unoptimized case, which is why we assigned to the `nooptimization` category (previously `unknown`).

> 
> (Related writing suggestion -- can you state the total number of bugs at the beginning of the paragraph in the manuscript? When I read it the first two times, I thought you were saying there were 18 total bugs, broken down by 3-3-1-1 (and a bunch of unknowns).

Thank you, we will incorporate this for the camera-ready version of the paper!

> 
> 1. It is a bit odd that the database columns don't quite match the table columns for Tables 2 and 3. Consider tweaking the schema, munging the query so that the columns match, or giving the mapping in the README.

To make the query for Table 3 consistent with the paper, we renamed the following values in the table `DBMS_BUGS`: `crash` to `crash (release)`, `debug` to `crash (debug)`, and `norec` to `logic`.
For Table 2, we simplified the query to `SELECT DATABASE, STATUS, count FROM DBMS_BUGS_STATUS WHERE count != 0;` and renamed `closed (not a bug)` to `closed (intended)` in the table `DBMS_BUGS`. The changes are reflected in commit https://github.com/mrigger/fse20/commit/7df45019b246f63221293dd869fbf9130be53282.

> 
> ## Reusable
> The documentation and structuring of this artifact is exemplary. However, I have some concerns "re-using it" and am not willing to grant the badge at the moment. Here are my issues:
> 
> 1. The documentation should indicate how long sqlancer will run if invoked without num-tries or timeout-seconds, and give your machine specs (or state that this information can be found in the paper).

We have realized that this info is missing based also on @a-nice-reviewer's feedback. Without options, SQLancer executes infinitely. Based on @a-nice-reviewer's feedback, we have added a paragraph to the `INSTALL.md` document to explain this (see https://github.com/mrigger/fse20/commit/cbeb56a8a817fafb3e9161aac30435908bdd9dac):

> The shortcut CTRL+C can be used to terminate SQLancer manually. If SQLancer does not find any bugs, it executes infinitely. The option `--num-tries` controls after how many bugs SQLancer terminates. Alternatively, the option `--timeout-seconds` can be used to specify the maximum duration that SQLancer is allowed to run.

In addition, we have now also updated the main repository's `README.md` with this information (see https://github.com/sqlancer/sqlancer/commit/313a87aa0dbb8329b92b20beebaec2d0aa5f5329). Note that we will include the latest version of SQLancer when preparing the camera-ready artifact version. Since SQLancer executes infinitely, we believe that the machine specs would not provide much additional insight. We executed SQLancer primarily on a ThinkPad P72 laptop with 6 cores (Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz).

> 2. The artifact suggests `--num-tries` or `--timeout-seconds` to control how long the program runs for. These do not work as of commit 41986ce4302b0 on the sqlancer project.
> 

Options that are supported by all DBMS testing implementations need to precede the name of the DBMS to be tested. So, for example, the following two commands work:

```
$ java -jar SQLancer-0.0.1-SNAPSHOT.jar --num-tries 5 sqlite3 --oracle NoREC
[2020/06/19 23:35:12] Executed 133566 queries (26691 queries/s; 1.00/s dbs, successful statements: 92%). Threads shut down: 0.
...
```
```
$ java -jar SQLancer-0.0.1-SNAPSHOT.jar --timeout-seconds 60 sqlite3 --oracle NoREC
[2020/06/22 11:35:35] Executed 99898 queries (19955 queries/s; 3.20/s dbs, successful statements: 92%). Threads shut down: 0.
```

We realize that this is confusing. In fact, a user of SQLancer has already opened [an issue on this](https://github.com/sqlancer/sqlancer/issues/31). This is a limitation of the option-parsing framework that we are using. For now, we have added the following note to the `INSTALL.md` (see https://github.com/mrigger/fse20/commit/449eed84a69377395227daa15adf26159449cc4e) and the `README.md` in the main repository (see https://github.com/sqlancer/sqlancer/commit/4c392214bf166fd86b051b3a4f37d8e3da38697b):

> Note that general options that are supported by all DBMS-testing implementations (e.g., `--num-threads`) need to precede the name of DBMS to be tested (e.g., `sqlite3`). Options that are supported only for specific DBMS (e.g., `--test-rtree` for SQLite3), or options for which each testing implementation provides different values (e.g. `--oracle NoREC`) need to go after the DBMS name.

We want to properly address this in the future (e.g., by changing the option parsing framework), and opened an issue to that end: https://github.com/sqlancer/sqlancer/issues/40.

**Comment by mrigger** [comment]
Thank you again for the feedback, @AnonReviewer626 and @a-nice-reviewer. For the discussion, I want to bring forward that there is already considerable additional evidence that the artifact is indeed functional and reusable:
* We released [SQLancer](https://github.com/sqlancer/sqlancer/) only on June 2, 2020, two days before the artifact submission deadline. As of June 22, it has been starred 464 times, and forked 35 times, indicating that there is significant interest in it.
* MonetDB Solutions implemented support for testing MonetDB in SQLancer, and has been using it to test MonetDB (see https://www.monetdb.org/bugzilla/buglist.cgi?bug_status=__all__&content=sqlancer&order=Importance&query_format=specific).
* We were informed that Alipay has been using SQLancer to find bugs in OceanBase.
* Yandex has started contributing to SQLancer, to test their DBMS ClickHouse (see https://github.com/sqlancer/sqlancer/pull/39).
* (PingCAP has developed [go-sqlancer](https://github.com/chaos-mesh/go-sqlancer), a tool to test TiDB based on the description of NoREC and the other testing approaches that we have implemented in SQLancer, with which they successfully found bugs, thus replicating our results.)

**Comment by AnonReviewer626** [comment]
@mrigger 

Thank you for your careful response to my concerns. I am happy to recommend that we grant all of the badges you requested:

*Available*, *Functional*, *Reusable*.

@kstolee @a-nice-reviewer and I now appear to be in agreement on these badges.

---------

> machine specs

The paper contains the sentence "While some bugs were found seconds after implementing a feature, others were found only after weeks". Understanding the machine specs might be helpful in interpreting this result.

> Option parsing order

No big deal. This is not uncommon in CLIs. Now that I have checked your CLI usage message, I think it is sensible as-is.

**Comment by kstolee** [comment]
Thanks everyone! 

@mrigger please cite your artifact using the DOI in the References section of your paper.

**Comment by gousiosg** [comment]
@mrigger Great work with the artifact (and the actual paper :-))
